=== indexdata/mod-cyclops/ramls/retrieve-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "A response to a CYCLOPS retrieve command, containing values from some fields in a set of objects",
  "type": "object",
  "properties": {
    "status": {
      "type": "string",
      "description": "Status of retrieveal, or 'error'"
    },
    "message": {
      "type": "string",
      "description": "Error message, only if status==error"
    },
    "fields": {
      "type": "array",
      "description": "Error message, only if status==error",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of a field included among the data rows"
          }
        },
        "additionalProperties": false,
        "required": [
          "name"
        ]
      }
    },
    "data": {
      "type": "array",
      "description": "List of returned data rows",
      "items": {
        "type": "object",
        "properties": {
          "values": {
	    "type": "array",
            "description": "XXX An array of data values, belonging to the fields named in the 'fields' top-level element",
	    "items": {
              "type": "string"
	    }
          }
        },
        "additionalProperties": false,
        "required": [
          "values"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "status"
  ]
}

=== indexdata/mod-cyclops/ramls/examples/retrieve-example.json
{
  "status": "ok",
  "message": "XXX This message should not exist, since status != 'error'",
  "fields": [
    {
      "name": "id"
    },
    {
      "name": "author"
    },
    {
      "name": "title"
    }
  ],
  "data": [
    {
      "values": [
        "123",
        "J. R. R. Tolkien",
        "The Lord of the Rings"
      ]
    },
    {
      "values": [
        "456",
        "Douglas Adams",
        "The Hitch-Hiker's Guide to the Galaxy"
      ]
    }
  ]
}
